export const personalityQuestions = [
  { id: 'q-pers-1', type: 'likert' as const, prompt: 'I feel energized after spending time with a large group of people.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { E: 3 } },
  { id: 'q-pers-2', type: 'likert' as const, prompt: 'I prefer spending my weekends relaxing quietly at home rather than attending social gatherings.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { I: 3 } },
  { id: 'q-pers-3', type: 'likert' as const, prompt: 'I am usually the one to start conversations with new classmates or colleagues.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { E: 3 } },
  { id: 'q-pers-4', type: 'likert' as const, prompt: 'I find prolonged social interactions exhausting and need alone time to recharge.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { I: 3 } },
  { id: 'q-pers-5', type: 'likert' as const, prompt: 'I enjoy being the center of attention in group settings or presentation panels.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { E: 3 } },
  { id: 'q-pers-6', type: 'likert' as const, prompt: 'I prefer expressing my thoughts in writing rather than speaking about them in public.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { I: 3 } },
  { id: 'q-pers-7', type: 'likert' as const, prompt: 'I actively seek out team activities, clubs, or group sports.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { E: 3 } },
  { id: 'q-pers-8', type: 'likert' as const, prompt: 'I pay close attention to concrete facts and details rather than theoretical possibilities.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { S: 3 } },
  { id: 'q-pers-9', type: 'likert' as const, prompt: 'I often find myself thinking about the future and what possibilities it holds.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { N: 3 } },
  { id: 'q-pers-10', type: 'likert' as const, prompt: 'I prefer learning practical skills that have immediate real-world applications.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { S: 3 } },
  { id: 'q-pers-11', type: 'likert' as const, prompt: 'I enjoy reading books, articles, or essays about abstract or philosophical ideas.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { N: 3 } },
  { id: 'q-pers-12', type: 'likert' as const, prompt: 'I rely on past experience to guide my decisions rather than relying on creative hunches.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { S: 3 } },
  { id: 'q-pers-13', type: 'likert' as const, prompt: 'I like to brainstorm original ideas and explore unconventional solutions to problems.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { N: 3 } },
  { id: 'q-pers-14', type: 'likert' as const, prompt: 'I am more interested in the actual, current state of things rather than what they could become.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { S: 3 } },
  { id: 'q-pers-15', type: 'likert' as const, prompt: 'I frequently use metaphors or analogies to explain my ideas to others.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { N: 3 } },
  { id: 'q-pers-16', type: 'likert' as const, prompt: 'I make decisions based on logical analysis and objective facts rather than personal feelings.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { T: 3 } },
  { id: 'q-pers-17', type: 'likert' as const, prompt: 'I prioritize empathy and maintaining harmony when resolving conflicts between friends.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { F: 3 } },
  { id: 'q-pers-18', type: 'likert' as const, prompt: 'I believe it is more important to be honest and direct than to worry about hurting someone\'s feelings.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { T: 3 } },
  { id: 'q-pers-19', type: 'likert' as const, prompt: 'I often make decisions based on my gut feelings or what feels right in my heart.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { F: 3 } },
  { id: 'q-pers-20', type: 'likert' as const, prompt: 'I enjoy analyzing data, frameworks, or systems to see how they work.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { T: 3 } },
  { id: 'q-pers-21', type: 'likert' as const, prompt: 'I am highly sensitive to the emotional atmosphere in a room or group.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { F: 3 } },
  { id: 'q-pers-22', type: 'likert' as const, prompt: 'I value justice and fairness over mercy and individual circumstances.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { T: 3 } },
  { id: 'q-pers-23', type: 'likert' as const, prompt: 'I prefer to have a detailed plan or schedule for my day-to-day activities.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { J: 3 } },
  { id: 'q-pers-24', type: 'likert' as const, prompt: 'I feel comfortable adapting to unexpected changes and being spontaneous.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { P: 3 } },
  { id: 'q-pers-25', type: 'likert' as const, prompt: 'I like to complete my assignments well before the deadline to avoid last-minute stress.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { J: 3 } },
  { id: 'q-pers-26', type: 'likert' as const, prompt: 'I work best under pressure when deadlines are close, as it motivates me.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { P: 3 } },
  { id: 'q-pers-27', type: 'likert' as const, prompt: 'I prefer to keep my options open rather than locking in plans early.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { P: 3 } },
  { id: 'q-pers-28', type: 'likert' as const, prompt: 'I feel satisfied when I cross items off my to-do list or finish planned tasks.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { J: 3 } },
  { id: 'q-pers-29', type: 'likert' as const, prompt: 'I keep my workspaces, folders, and documents organized and tidy.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { J: 3 } },
  { id: 'q-pers-30', type: 'likert' as const, prompt: 'I enjoy starting new projects more than wrapping up old or completed ones.', minLabel: 'Disagree', maxLabel: 'Agree', weights: { P: 3 } }
];
